Airplane game
PTWA-NPO/PTWASpecialEducation pull request #14
Opened 2024-10-11 09:21 UTC by RayUTwolf

遊戲機制基本完善 需要請設計師畫素材(背景、飛機、放選項的雲朵)

2024-10-15 03:24 UTC, RayUTwolf commented
完成數線component 若確定使用沒問題NumberLineTester.vue可以刪掉

2024-10-15 07:31 UTC, Rduanchen requested changes
我在以下的檔案中留了一些註解，麻煩再修正
1. sky.jpg
2. Airplane.vue
3. DragInNumberLine.vue

2024-10-15 07:31 UTC, Rduanchen commented on src/views/GameTemplate/Airplane.vue
> +const Background = document.createElement("img");
建議不要將程式碼寫在export default 外面，同時，使用 Image()，盡量不要有直接操作DOM的行為

放在created 裡面
const BackGround = new window.Image()
BackGround.src = GamesGetAssetsFile("Dev02_Airplane", "sky.jpg");

2024-10-15 07:31 UTC, Rduanchen commented on src/views/GameTemplate/Airplane.vue
> +    collisionDetect() {
這個函數處理的事情過多了，建議拆分成 collisionDetect 以及 checkAnswer 兩個函數

2024-10-15 07:31 UTC, Rduanchen commented on src/views/GameTemplate/Airplane.vue
> +            this.$emit("add-record", ["#", this.configOptions[i].text, "正確"]);
前面的 # 是什麼意思呢?

2024-10-15 07:31 UTC, Rduanchen commented on src/utilitys/canvasTools.js
看起來挺讚的

2024-10-15 07:31 UTC, Rduanchen commented on src/assets/Games/Dev02_Airplane/sky.jpg
我個人會建議這放在System 裡面

path : @/assets/System/Airplane
使用函數 get_assets.js

裡面的這個函數
export function getSystemAssets(url, service) {
   return new URL(`../assets/System/${service}/${url}`, import.meta.url).href
}

2024-10-15 07:38 UTC, Rduanchen commented on src/views/GameTemplate/Airplane.vue
> +            this.$emit("add-record", ["#", this.configOptions[i].text, "正確"]);
[題目+選項, 正確答案, 判斷]

2024-10-23 00:50 UTC, Rduanchen reviewed
看起來不錯，感謝

2024-10-28 06:17 UTC, merged