新增分數計算的遊戲及題目還有數字鍵盤
PTWA-NPO/PTWASpecialEducation pull request #25
Opened 2024-11-22 07:41 UTC by 2min0623

2024-11-27 10:12 UTC, Rduanchen requested changes
有許多地方需要修正，我都有進行標註，請一個個修正，並且麻煩一個個回應我的註解，感謝~

感覺妳對 slot-components 的想像跟我有些不同，大部分的comment 都是跟components 的通訊規格定義有關係。

2024-12-06 06:12 UTC, 2min0623 commented on src/components/FloatNumPad.vue
> +    data: {
修改完成

2024-12-06 06:13 UTC, 2min0623 commented on src/components/FractionDisplay.vue
> +    data: {
修改完成

2024-12-06 06:13 UTC, 2min0623 commented on src/components/FractionForAnswer.vue
> +  props: {
修改完成

2024-12-06 06:13 UTC, 2min0623 commented on src/components/FractionForAnswer.vue
> +      maxInputLength: 4, // 輸入框最大字符數
我移除了

2024-12-06 06:14 UTC, 2min0623 commented on src/views/GameTemplate/NumberLock.vue
> -          @ReplyAnswer="downReply"
修改完成

2024-12-06 06:15 UTC, 2min0623 commented on src/views/GameTemplate/FractionArithmetic.vue
有四個教案有用到

2024-12-06 06:15 UTC, 2min0623 commented on src/views/GameTemplate/FractionArithmetic.vue
> +        this.$emit("next-question", true);
修改完成

2024-12-06 06:15 UTC, 2min0623 commented on src/views/GameTemplate/ClassifyGame.vue
> +const FAILURE_MESSAGES = {
修改完成

2024-12-06 06:16 UTC, 2min0623 commented on src/views/GameTemplate/ClassifyGame.vue
> +    emitNextQuestion() {
我改成直接emit了

2024-12-11 08:30 UTC, Rduanchen requested changes

2024-12-11 08:30 UTC, Rduanchen commented on src/views/GameTemplate/FractionArithmetic.vue
> +        this.$emit("next-question", true);
這個方法似乎錯了

2024-12-11 08:30 UTC, Rduanchen commented on src/views/GameTemplate/FractionArithmetic.vue
> +        this.$emit("next-question", true);
參考一下其他的遊戲是怎麼寫的

2024-12-13 05:32 UTC, 2min0623 commented on src/views/GameTemplate/NumberLock.vue
> -      <div class="number-pad" v-if="ShowPad && this.GameConfig.layout.pad">
修改完畢

2024-12-13 05:33 UTC, 2min0623 commented on src/components/FractionChart.vue
> +  beforeMount() {
修改完成

2024-12-13 07:21 UTC, merged